fixes

diff --git a/tools/deploy-to-openshift.yaml b/tools/deploy-to-openshift.yaml
--- a/tools/deploy-to-openshift.yaml
+++ b/tools/deploy-to-openshift.yaml
@@ -34,6 +34,7 @@ tools:
       project="{{.project}}"
       namespace="${project}-${environment}"
       helm_chart_url="{{.helm_chart_url}}"
+      helm_release_name="${project}-${environment}-release"
 
       # Default Helm chart URL if not provided
       if [ -z "$helm_chart_url" ]; then
@@ -56,7 +57,7 @@ tools:
 
       # Deploy the Helm chart
       debug "Deploying Helm chart from $helm_chart_url to namespace $namespace"
-      helm install --generate-name -f $helm_chart_url -n $namespace || error "Failed to deploy Helm chart to namespace $namespace"
+      helm install $helm_release_name $helm_chart_url -n $namespace || error "Failed to deploy Helm chart to namespace $namespace"
 
       # Verify the deployment
       debug "Verifying the deployment in namespace $namespace"
